spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 956464906378-ksrqt4kb7s7kv4a7q1qfa3qnpj65nclt.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email

          naver:
            client-id: jcBXYMvJylpD4lkEHGJK
            client-secret: MQcCVfSNkP
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver

          kakao:
            client-id: 4e16152617fcf54ee929e4f0aa6f2563
            client-secret: VgsjoMhNvBmYmFLQhc8DDN4FA4WToqQq
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image
            client-name: Kakao

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
