jwt:
  secret: b68l1FyGcgq+wdIVM6UkOgG9CiZrkgwRvpki3frHZwo=

spring:
  profiles:
    group:
      "local":
        - "oauth"
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/instrument
    username : root
    password : 4492776
  servlet:
    multipart:
      maxFileSize: 10MB # ?? ??? ?? ??
      maxRequestSize: 30MB  # ? ?? ?? ??? ?? ??
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.naver.com
    port: 465
    username: nelap12345@naver.com
    password: qkffkr123$
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com
  data:
    redis:
      host: localhost
      port: 6379

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true