jwt:
  secret: b68l1FyGcgq+wdIVM6UkOgG9CiZrkgwRvpki3frHZwo=


spring:
  profiles:
    group:
      "local":
        - "oauth"
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/instrument
    username : root
    password : gudtjr32
  servlet:
    multipart:
      maxFileSize: 10MB # ?? ??? ?? ??
      maxRequestSize: 30MB  # ? ?? ?? ??? ?? ??
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true